services:

  task-service:
    build:
      context: .
      dockerfile: ./services/task-service/Dockerfile
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    environment:
      - PORT=${TASK_SERVICE_PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${TASK_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skingen-network
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - PORT=${GATEWAY_PORT}
    networks:
      - skingen-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${ROOT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ROOT_POSTGRES_PASSWORD}
      - TASK_SERVICE_POSTGRES_USER=${TASK_SERVICE_POSTGRES_USER}
      - TASK_SERVICE_POSTGRES_PASSWORD=${TASK_SERVICE_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-setup/init-task-service.sh:/docker-entrypoint-initdb.d/01-init-roles-and-schemas.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ROOT_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skingen-network

networks:
  skingen-network:
    driver: bridge

volumes:
  postgres_data:
