services:

  task-service:
    build:
      context: .
      dockerfile: ./services/task-service/Dockerfile
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    environment:
      - PORT=${TASK_SERVICE_PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${TASK_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - skingen-network
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - PORT=${GATEWAY_PORT}
    networks:
      - skingen-network

networks:
  skingen-network:
    driver: bridge
