services:
  model-server:
    build:
      context: .
      dockerfile: ./services/model-server/Dockerfile
    ports:
      - "${MODEL_SERVER_PORT}:${MODEL_SERVER_PORT}"
    environment:
      - PORT=${MODEL_SERVER_PORT}
      - MODEL_ID=${MODEL_ID}
      - MODEL_DIR=/model
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - models:/model
    networks:
      - skingen-network
  worker:
    build:
      context: .
      dockerfile: ./services/worker/Dockerfile
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    environment:
      - SERVICE_NAME=worker
      - PORT=${WORKER_PORT}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@queue:${RABBITMQ_PORT}
      - MODEL_SERVER_URL=model-server:${MODEL_SERVER_PORT}
      - GENERATE_IMAGE_QUEUE=${GENERATE_IMAGE_QUEUE}
      - TASK_RESULT_QUEUE=${TASK_RESULT_QUEUE}
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=${MINIO_WORKER_USER}
      - S3_SECRET_KEY=${MINIO_WORKER_PASSWORD}
      - S3_BUCKET=${SKIN_IMAGES_BUCKET}
    depends_on:
      queue:
        condition: service_healthy
    networks:
      - skingen-network

  task-service:
    build:
      context: .
      dockerfile: ./services/task-service/Dockerfile
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    environment:
      - SERVICE_NAME=task-service
      - PORT=${TASK_SERVICE_PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${TASK_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@queue:${RABBITMQ_PORT}
      - GENERATE_IMAGE_QUEUE=${GENERATE_IMAGE_QUEUE}
      - TASK_RESULT_QUEUE=${TASK_RESULT_QUEUE}
    depends_on:
      migrator:
        condition: service_completed_successfully
      queue:
        condition: service_healthy
    networks:
      - skingen-network
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - SERVICE_NAME=gateway
      - PORT=${GATEWAY_PORT}
      - TASK_SERVICE_URL=task-service:${TASK_SERVICE_PORT}
    networks:
      - skingen-network
    depends_on:
      - task-service
  migrator:
    image: migrate/migrate:latest
    command: [ "-path", "/migrations", "-database", "postgres://${ROOT_POSTGRES_USER}:${ROOT_POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up" ]
    volumes:
      - ./database-setup/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skingen-network
  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${ROOT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ROOT_POSTGRES_PASSWORD}
      - TASK_SERVICE_POSTGRES_USER=${TASK_SERVICE_POSTGRES_USER}
      - TASK_SERVICE_POSTGRES_PASSWORD=${TASK_SERVICE_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-setup/init-task-service.sh:/docker-entrypoint-initdb.d/01-init-roles-and-schemas.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ROOT_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skingen-network

  queue:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skingen-network

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - skingen-network
    healthcheck:
      test: [ "CMD", "mc", "ls", "myminio" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-client:
    image: minio/mc
    entrypoint: /app/setup.sh
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - SKIN_IMAGES_BUCKET=${SKIN_IMAGES_BUCKET}
      - MINIO_TASK_SERVICE_USER=${MINIO_TASK_SERVICE_USER}
      - MINIO_TASK_SERVICE_PASSWORD=${MINIO_TASK_SERVICE_PASSWORD}
      - MINIO_WORKER_USER=${MINIO_WORKER_USER}
      - MINIO_WORKER_PASSWORD=${MINIO_WORKER_PASSWORD}
    volumes:
      - ./minio-setup:/app
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - skingen-network

networks:
  skingen-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  models:
  minio_data:
