#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $TASK_SERVICE_POSTGRES_USER WITH PASSWORD '$TASK_SERVICE_POSTGRES_PASSWORD';

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $TASK_SERVICE_POSTGRES_USER;

    CREATE SCHEMA IF NOT EXISTS task_service AUTHORIZATION $TASK_SERVICE_POSTGRES_USER;

    ALTER USER $TASK_SERVICE_POSTGRES_USER SET search_path = task_service, public;

    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA task_service
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $TASK_SERVICE_POSTGRES_USER;

    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA task_service
    GRANT USAGE, SELECT ON SEQUENCES TO $TASK_SERVICE_POSTGRES_USER;
EOSQL