# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x08model.v1\"&\n\x14GenerateImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"+\n\x15GenerateImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32\x62\n\x0eImageGenerator\x12P\n\rGenerateImage\x12\x1e.model.v1.GenerateImageRequest\x1a\x1f.model.v1.GenerateImageResponseB+Z)/services/model-server/generated/model/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)/services/model-server/generated/model/v1'
  _globals['_GENERATEIMAGEREQUEST']._serialized_start=25
  _globals['_GENERATEIMAGEREQUEST']._serialized_end=63
  _globals['_GENERATEIMAGERESPONSE']._serialized_start=65
  _globals['_GENERATEIMAGERESPONSE']._serialized_end=108
  _globals['_IMAGEGENERATOR']._serialized_start=110
  _globals['_IMAGEGENERATOR']._serialized_end=208
# @@protoc_insertion_point(module_scope)
